### ISSUE TITLE
Newest update failed on backup step, now no longer showing as installed application

### ISSUE THREAD

**Issue by elenners** [YunoHost-Apps/misskey_ynh#101]
### Describe the bug

I logged into Yunohost and updated my packages. There was also an update for Misskey so I chose to install it. It hung on the app backup step and I let it sit for well over an hour. I hard refreshed the page and then when it didn't load I restarted the server.

Upon reboot, I get the error pop up below when I go into the Updates section, and Misskey is no longer showing in the installed application list. The site is still up though.

<img width="770" alt="Screen Shot 2022-07-01 at 6 08 02 PM" src="https://user-images.githubusercontent.com/63966511/176977088-3938c128-5856-48a8-8fd6-a6170308152d.png">
Error message that comes up every time I access the Updates page

<img width="1150" alt="Screen Shot 2022-07-01 at 6 12 24 PM" src="https://user-images.githubusercontent.com/63966511/176977100-e043dd5a-36f6-44c3-acfc-71c4aea8529d.png">
Misskey no longer shows as installed but the site is up and functioning

### Context

- Hardware: Contabo VPS on Debian 10
- YunoHost version: 4.3.6.3
- I have access to my server: Through SSH
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: No
  - If yes, please explain: --
- Using, or trying to install package version/branch: Misskey 12.110.1~ynh2
- If upgrading, current package version: 12.110.1~ynh1

### Steps to reproduce

   1. *Go to Updates page*
   2. *Click on Install for Misskey*
   3. *The window showing the progress will display and get stuck on backing up app*
   4. *See error after restart*

### Expected behavior

The Misskey update should have completed and been applied successfully. The app should still display as an installed application.

### Logs

https://paste.yunohost.org/raw/ekonaqugap - apparently the update was successful so it's odd

**Comment by memo-567** [comment]
`manifest.json` seems to be, for whatever reason, defective according to the error message.

What I can think of, at the moment, would be to manually copy the `manifest.json` or its content  from [Git](https://github.com/YunoHost-Apps/misskey_ynh/blob/master/manifest.json) to the `/etc/yunohost/apps/misskey/` directory or file, to pass this error message.

As with any major change, be sure to make a full backup first.

**Comment by memo-567** [comment]
**Addendum:**
A backup can take a long time, depending on the amount of data. 
Aborting due to an early restart or reset can lead to this error.

**Comment by memo-567** [comment]
Since there are no further reactions, I assume that the problem is solved.

If not, the issue can be reopened at any time.

**Comment by elenners** [comment]
Is it possible to provide a step-by-step to correct this issue? I have never been able to
