### ISSUE TITLE
I can't add an avatar to my Misskey profile settings

### ISSUE THREAD

**Issue by aasandr0** [YunoHost-Apps/misskey_ynh#140]
**Environment:**
1. Win10
2. Brave Desktop  v1.46.134, (Chromium to 108.0.5359.94)
3. Yunohost Misskey 12.119.0~ynh1

**Steps:**
1. Log in to your user account;
2. Go to profile settings, at: https://$instance.tld/settings/profile
Click on the button responsible for the "Change avatar" function
4. Select a photo.

**Expected result**: the photo is uploaded to the user's drive and set as an avatar;

**Actual result**: the photo is uploaded to the user's drive, but the avatar is not changed and remains in the "eternal download.
![image](https://user-images.githubusercontent.com/119762559/205463153-a2ab4e3e-5863-454b-9e43-f219496ceae5.png)
![image](https://user-images.githubusercontent.com/119762559/205463157-be723ea1-d006-4644-afad-4c084d92c491.png)

**Comment by memo-567** [comment]
This seems to be more of a MIsskey than a YunoHost issue, and it's probably better to open an issue there:

https://github.com/misskey-dev/misskey

Irrespective of this, information on which hardware the Misskey instance is running on would also be important.

**Comment by aasandr0** [comment]
> This seems to be more of a MIsskey than a YunoHost issue, and it's probably better to open an issue there:
> 
> https://github.com/misskey-dev/misskey
> 
> Irrespective of this, information on which hardware the Misskey instance is running on would also be important.

Okay, I hear you. Sorry for the wrong address, I'm not a developer or an experienced administrator. I will write there on this issue.

Misskey installed on Debian 11, kernel version and architecture: 5.10.0-19-amd64 #1 SMP Debian 5.10.149-2 (2022-10-21) x86_64 GNU/Linux

**Comment by memo-567** [comment]
No problem, even if I couldn't help you here, I'm glad I could give you this hint.
