### ISSUE TITLE
A successful backup of Misskey cannot be performed.

### ISSUE THREAD

**Issue by cdedert** [YunoHost-Apps/misskey_ynh#149]
### Describe the bug

A successful backup of Misskey cannot be performed.

### Context

- Hardware: Old computer 
- YunoHost version:  11.1.15 
- I have access to my server:  Through SSH & through the webadmin 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no 
- Using, or trying to install package version/branch: 12.119.2~ynh1

### Steps to reproduce

I'm trying to perform a backup of Misskey. First, I tried to use the webadmin and it seems to have locked up the webadmin. Then, I went to the terminal and tried to back up Misskey using _yunohost backup create --apps misskey._ It tries to do the backup, but ultimately fails with this wording: 
__Error: Could not add the files '/var/www/misskey' (named in the archive 'apps/misskey/backup/var/www/misskey') to be backed up into the compressed archive '/home/yunohost.backup/archives/20230331-025254.tar'
Info: The operation 'Create a backup archive' could not be completed. Please share the full log of this operation using the command 'yunohost log share 20230331-025254-backup_create' to get help
Error: Could not create the backup archive_
_

### Expected behavior

I would expect a successful backup to be performed. I would then be able to access the backup from the webadmin and download the backup.

What actually happens, is there seems to be a backup file created if I use the terminal to view the folder at dir /home/yunohost.backup/archives, but there is no .json file. The webadmin then takes several hours to populate the backup section or sometimes times out with a 504 Timeout. I can successfully backup other apps. 
I have tried to back up Misskey several times and I get the same result. There will be 20+gb .tar files created, but no .json file. There is over 100gb of storage left on my drive. I have deleted several of the failed attempts in order to create space for a successful backup.

### Logs

https://paste.yunohost.org/raw/ilihoqusap

**Comment by cdedert** [comment]
Can anyone help me with this?

**Comment by lapineige** [comment]
So the actual error message is :
```
2023-03-30 21:57:28,770: DEBUG - Creating the backup TAR archive...
2023-03-30 22:44:02,560: ERROR - Could not add the files '/var/www/misskey' (named in the archive 'apps/misskey/backup/var/www/misskey') to be backed up into the compressed archive '/home/yunohost.backup/archives/20230331-025254.tar'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/yunohost/backup.py", line 1964, in backup
    tar.add(path["source"], arcname=path["dest"])
  File "/usr/lib/python3.9/tarfile.py", line 1985, in add
    self.add(os.path.join(name, f), os.path.join(arcname, f),
  File "/usr/lib/python3.9/tarfile.py", line 1985, in add
    self.add(os.path.join(name, f), os.path.join(arcname, f),
  File "/usr/lib/python3.9/tarfile.py", line 1963, in add
    tarinfo = self.gettarinfo(name, arcname)
  File "/usr/lib/python3.9/tarfile.py", line 1842, in gettarinfo
    statres = os.lstat(name)
FileNotFoundError: [Errno 2] No such file or directory: '/var/www/misskey/files/4e5af59c-f1dc-4cad-9e3c-708d237e0abc'
```

I don't know what it is supposed to do.
Can you check that file exist ?

**Comment by cdedert** [comment]
That file (/var/www/misskey/files/4e5af59c-f1dc-4cad-9e3c-708d237e0abc) is actually missing. I wonder what would happen if I created a file with that name and left it blank (since I don't know what belongs in it) and then tried to do a backup?

**Comment by lapineige** [comment]
I wonder why it tries to backup it if it does not exists… how and when did it list it ? 🤔

This might be a media file, I'm not sure it's a big deal if it's empty, but I can't tell the possible consequences if you try to do so.
Can you check another randomly named file in that folder to check if it's a media file ?
