### ISSUE TITLE
"DEV BUILD" flashes in the upper left corner after update to 12.108.1

### ISSUE THREAD

**Issue by memo-567** [YunoHost-Apps/misskey_ynh#56]
First, thanks for the good work and the quick update to v 12.108.1.

Everything seems to be working proper, except a flashing message  "DEV BUILD" in the top left corner on all pages.

![dev-build](https://user-images.githubusercontent.com/58190287/158434261-6c4ed56a-c07e-407b-82b8-a5a92d6b6e05.jpg)

**Comment by ericgaspar** [comment]
Should be fixed with #55

**Comment by memo-567** [comment]
Works perfect - thanks 👍
