### ISSUE TITLE
Script error when installing on RPI 4.

### ISSUE THREAD

**Issue by freejassange** [YunoHost-Apps/misskey_ynh#60]
I am a little new to Yuno and would like to use Misskey. The log is attached.
[misskey_script_error.txt](https://github.com/YunoHost-Apps/misskey_ynh/files/8377022/misskey_script_error.txt)

**Comment by memo-567** [comment]
Did you try to update the Debian system first?

**Comment by freejassange** [comment]
I see now that I am running Buster. I will figure out how to upgrade to Bullseye and try again. Thank you for the feedback.

**Comment by memo-567** [comment]
That shouldn't be the reason. Misskey also runs on Buster here without any problems.
I meant the Buster upgrade with the current packages.

**Comment by memo-567** [comment]
It looks in the log file as if your RP4 does not meet the system requirements for the required Cypress:

> "The Cypress App could not be installed. Your machine does not meet the operating system requirements."

**Comment by freejassange** [comment]
All my packages are updated, but it failed to install on second try. I figured some dep was unable to run on Raspbian. It looks like Cypress requires 64 bit processor. I am prepping an X86 64bit system and will try it there. It might be good to note this limitation in the read_me for others who might attempt this. Thank you for looking at the issue. I look forward to Misskey later.

**Comment by memo-567** [comment]
You're welcome and good luck with it.

**Comment by tituspijean** [comment]
I would suggest to create a test on the architecture (`$YNH_ARCH`) to stop the installation script if the system is not x64.
