### ISSUE TITLE
error updating

### ISSUE THREAD

**Issue by h3ndrik** [YunoHost-Apps/misskey_ynh#66]
misskey fails to update. here's the log:

https://paste.yunohost.org/raw/dajicakomi

I believe this is due to this module not being found:
```
Module not found: Error: Can't resolve 'crc-32' in '/var/www/misskey/packages/client/src/pages/reversi'
[...]
webpack 5.70.0 compiled with 1 error and 39 warnings in 78321 ms
[...]
Error: Command failed with exit code 1: npm run build
```

Also there are lots of error messages before. I'm not sure what's happening there.

affected: `12.108.1~ynh2` and `12.109.2~ynh1` (i'm currently (stuck) on `12.102.1~ynh1`)

**Comment by memo-567** [comment]
Have you already tested an upgrade with the new YunoHost Misskey version?

**Comment by h3ndrik** [comment]
yes. tried an upgrade to the latest version:
https://paste.yunohost.org/raw/fagoyujugu

**Comment by memo-567** [comment]
Several reasons for the unsuccessful upgrade are listed in the log file.

However, it doesn't surprise me. Is your version **12.102.1** a total of sixteen (!) upgrades behind **12.110.1**.

https://github.com/misskey-dev/misskey/releases

Incompatibilities in trying to do these 16 upgrades in just one step are understandable.

Unfortunately, I don't see a way to update version 12.102.1.

**Comment by h3ndrik** [comment]
there is one version (12.107.0) between 102.1 and 108 i might have skipped?!

any info on this 'module not found'?
