### ISSUE TITLE
Several suggestions for README

### ISSUE THREAD

**Issue by 4ioskd** [YunoHost-Apps/misskey_ynh#71]
Hello, I'm DignifiedSilence. Misskey contributor.
I have several suggestions below to improve this repo's README.

1. In the section of "Screenshots", its image( screenshot of web client ) is came from Misskey v11 or v10. It needs to be replaced by a new one.

2. In the section of "Documententation and resources", Official app website: https://join.misskey.page is an old one. The new Misskey official website is https://misskey-hub.net/ .

3. "misskey.io" isn't Misskey official instance and not related to Misskey project. In my opinion, the new Misskey official website is recommended in About.

**Comment by ericgaspar** [comment]
Thanks for reporting.
Can you point to a screenshot that we can use ?

**Comment by 4ioskd** [comment]
You can use this screenshot of Misskey:
https://github.com/misskey-dev/misskey-hub/blob/main/src/.vuepress/public/screenshot-desktop.png

This image is used on Misskey Official Website which is under MIT License.

**Comment by ericgaspar** [comment]
Thanks for the link. The 3 suggestions have been applied.

**Comment by 4ioskd** [comment]
Thank you for accepting my suggestions!
