### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by sthaydn** [YunoHost-Apps/misskey_ynh#78]
Hi there,

I wanted to install Misskey on the latest stable, but I do get:
INFO *        [core boot]        Welcome to Misskey!
INFO *        [core boot]        Misskey v12.110.0
INFO *        [core boot env]        NODE_ENV: production
INFO *        [core boot env]        You do not have root privileges
INFO *        [core boot nodejs]        Version v16.13.1 detected.
ERR  *        [core boot nodejs]        At least Node.js v16.14.0 required!
INFO *        [core]        The process is going to exit with code 1

What could I do?

Regards,

Stefan

**Comment by ericgaspar** [comment]
Can you try to install from the testing branch?
`sudo yunohost app install https://github.com/YunoHost-Apps/misskey_ynh/tree/testing`

**Comment by sthaydn** [comment]
Thank you very much. It is working now.
