### ISSUE TITLE
E-Mail settings

### ISSUE THREAD

**Issue by sthaydn** [YunoHost-Apps/misskey_ynh#84]
Hi there,

what settings I should use when enabling the E-Mail-Server inside Misskey? When using the mailsystem from yunohost (smtp adress, port 587, no authentication) it doesn't seem to work. When using another server outside yunohost it works. But it would make sense to use the yunohost server.

Error message:
Internal error occurred. Please contact us if the
error persists.
5d37dbcb-891e-41ca-a3d6-e690c97775ac

Regards,

Stefan

**Comment by memo-567** [comment]
Hi Stefan.

You don't use built-in mail servers at Misskey, but SMTP to remote mail servers like Gmail or other mail providers.

However, you can also use a mail account within Yunohost, but you must authorize yourself with a username and password.

**Comment by sthaydn** [comment]
Hi Memo,

thanks for your reply. I want to use misskey on my yunohost server with the smtp from this yunohost server. This should be default I guess?

How did you setup the mailsettings inside misskey with yunohost?

**Comment by sthaydn** [comment]
Ok, it seems I need to have authentication used. Thanks, @memo-567!
