### ISSUE TITLE
can't upload large files > 1M

### ISSUE THREAD

**Issue by jarod5001** [YunoHost-Apps/misskey_ynh#87]
I have misskey 12.110.0-ynh2 installed in a dedicated domain.
can't upload files larger than 1M

nginx log :
`2022/04/23 14:00:00 [error] 3659#3659: *238991 client intended to send too large body: 1996918 bytes, client: 197.xxx.xxx.xxx, server: friends.domain.me, request: "POST /api/drive/files/create HTTP/2.0", host: "friends.domain.me", referrer: "https://friends.domain.me/"
`
@memo-567

**Comment by memo-567** [comment]
As far as I know, the maximum upload size is actually still 1 MB and cannot be adjusted at the moment.

A larger image only makes sense if images are automatically reduced in size.

This will probably be possible in the future when this improvement is integrated.

**Comment by memo-567** [comment]
Should be fixed with the next update.
