### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by OniriCorpe** [YunoHost-Apps/misskey_ynh#9]
### Describe the bug
I'm unable to install misskey at all on the latest ynh version

### Context

- Hardware: VM on Proxmox. 1 CPU (2 cores) and 6 GB of RAM
- YunoHost version: 4.2.5.2 (stable and latest atm)
- I have access to my server: Through SSH, through the webadmin, direct access via keyboard / screen but **the webmin for this attempt of install**
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance ?: no
- Using, or trying to install package version/branch: latest atm

### Steps to reproduce

- *If you performed a command from the CLI, the command itself is enough. For example:*
    ```sh
    sudo yunohost app install misskey
    ```
- *If you used the webadmin, please perform the equivalent command from the CLI first.*
- *If the error occurs in your browser, explain what you did:*
   1. *Go to 'Application'*
   2. *Click on 'Install'*
   3. *Search for 'Misskey'*
   4. *Click on 'Install'*
   5. *Choose 'test.example.TLD'*
   6. *Wait the installation process*
   7. *See the error*

### Expected behavior

Misskey to be installated on the selected domain name.

### Logs

https://paste.yunohost.org/raw/owukotogaz

**Comment by oufmilo** [comment]
Can you try the testing branch with this command:

sudo yunohost app install https://github.com/YunoHost-Apps/misskey_ynh/tree/testing --debug

**Comment by OniriCorpe** [comment]
it works now with the master branch, thanks and sorry for the late reply! :)
